Select
    rep.KLEARNERPREINSTREPORTID,
    rep.KSTUDENTBUSENTID,
    rep.FEXAMNO,
    rep.FSCHOOLSUBJECTCODE,
    rep.FMATRICYEAR,
    sna.NAME,
    rep.PERCENTAGE,
    fnc.CODELONGDESCRIPTION As ACHIEVEMENT,
    rec.CODELONGDESCRIPTION As STATUS,
    exc.CODELONGDESCRIPTION As EXAM_LANGUAGE,
    rep.ISCONDONATIONAPPLIED,
    rep.ISREPEATINGSUBJ,
    rep.EDUCATIONDEPTSCHOOLSUBJCODE
From
    LEARNEREDUCATIONDEPTREPORT rep Left Join
    SCHOOLSUBJECTNAME sna On sna.KSCHOOLSUBJECTCODE = rep.FSCHOOLSUBJECTCODE
            And sna.KSYSTEMLANGUAGECODEID = 3 Left Join
    CODEDESCRIPTION fnc On fnc.KCODEDESCID = rep.FNSCCODEID
            And fnc.KSYSTEMLANGUAGECODEID = 3 Left Join
    CODEDESCRIPTION rec On rec.KCODEDESCID = rep.FSUBJRESULTCODEID
            And rec.KSYSTEMLANGUAGECODEID = 3 Left Join
    CODEDESCRIPTION exc On exc.KCODEDESCID = rep.FSUBJEXAMPAPERLOLTCODEID
            And exc.KSYSTEMLANGUAGECODEID = 3
Order By
    rep.KSTUDENTBUSENTID,
    sna.NAME