Select
    sa.KAPPLICATIONID As APP_ID,
    sa.FSTUDENTBUSENTID As STUDENT,
    Case
        When sa.FSITEORGUNITNUMBER = -9
        Then 'MC'
        When sa.FSITEORGUNITNUMBER = -2
        Then 'VC'
        Else 'PC'
    End As CAMPUS,
    sa.FCONDITIONALADMISSIONCODEID As CA_CODE,
    Upper(codcon.CODELONGDESCRIPTION) As CONDITIONAL_ADMISSION,
    sa.FAPPLSOURCECODEID As AS_CODE,
    Upper(codsou.CODELONGDESCRIPTION) As APPLICATION_SOURCE,
    sa.APPLYEAR,
    sa.WWWSUBMITUSER As WWW_USER,
    sa.WWWSUBMITDATE As WWW_SUBMIT,
    sa.WWWAPPLICATIONDATE As WWW_DATE,
    sa.AUDITDATETIME As LAST_DATETIME,
    sa.FAUDITSYSTEMFUNCTIONID As LAST_SYSFUNCTION,
    sa.FAUDITUSERCODE As LAST_USERCODE,
    sas.FAPPLICATIONSTATUSCODEID As AST_CODE,
    Upper(codsas.CODELONGDESCRIPTION) As APPLICATION_STATUS,
    sas.AUDITDATETIME As AUDIT_DATETIME,
    sas.FAUDITSYSTEMFUNCTIONID As AUDIT_SYSTEMFUNCTIONID,
    sas.FAUDITUSERCODE As AUDIT_USERCODE,
    su.FUSERBUSINESSENTITYID As EMPLOYEE,
    To_Char(Cast(sas.AUDITDATETIME As Date), 'hh24:mi:ss') As AUDITDATETIME_TIME
From
    STUDYAPPLICATION sa Inner Join
    STUDYAPPLSTATUS sas On sas.FAPPLICATIONID = sa.KAPPLICATIONID Left Join
    CODEDESCRIPTION codsas On codsas.KCODEDESCID = sas.FAPPLICATIONSTATUSCODEID
            And codsas.KSYSTEMLANGUAGECODE = 3 Left Join
    SYSTEMUSER su On su.KUSERCODE = sas.FAUDITUSERCODE
            And sas.AUDITDATETIME Between su.STARTDATE And SysDate Left Join
    CODEDESCRIPTION codcon On codcon.KCODEDESCID = sa.FCONDITIONALADMISSIONCODEID
            And codcon.KSYSTEMLANGUAGECODE = 3 Left Join
    CODEDESCRIPTION codsou On codsou.KCODEDESCID = sa.FAPPLSOURCECODEID
            And codsou.KSYSTEMLANGUAGECODE = 3
Where
    sa.APPLYEAR = 2024
Order By
    AUDIT_DATETIME