Select
    ql.KQUALLEVELENROLSTUDLOGID,
    ql.KENROLSTUDID,
    ql.KSTUDBUSENTID,
    ql.STARTDATE,
    ql.ENDDATE,
    ql.FSTUDYCENTREBUSENTID,
    ql.DATEENROL,
    ql.FENROLMENTPRESENTATIONID,
    ql.FPROGRAMAPID,
    Upper(bl.CODELONGDESCRIPTION) As BLACKLIST,
    Upper(sa.CODELONGDESCRIPTION) As STUDENT_ACTIVE,
    ql.FENTRYLEVELCODEID,
    Upper(el.CODELONGDESCRIPTION) As ENTRY_LEVEL,
    Upper(la.CODELONGDESCRIPTION) As LOG_ACTION,
    ql.ISMAINQUALLEVEL,
    ql.ENROLACADEMICYEAR,
    ql.ENROLHISTORYYEAR,
    ql.DATEQUALLEVELSTARTED,
    ql.ISCONDITIONALREG,
    ql.LOCKSTAMP,
    ql.AUDITDATETIME,
    ql.FAUDITSYSTEMFUNCTIONID,
    ql.FAUDITUSERCODE,
    SYSTEMUSER.FUSERBUSINESSENTITYID As NWU_NUMBER
From
    QUALLEVELENROLSTUDLOG ql Left Join
    CODEDESCRIPTION bl On bl.KCODEDESCID = ql.FBLACKLISTCODEID
            And bl.KSYSTEMLANGUAGECODEID = 3 Left Join
    CODEDESCRIPTION sa On sa.KCODEDESCID = ql.FSTUDACTIVECODEID
            And sa.KSYSTEMLANGUAGECODEID = 3 Left Join
    CODEDESCRIPTION el On el.KCODEDESCID = ql.FENTRYLEVELCODEID
            And el.KSYSTEMLANGUAGECODEID = 3 Inner Join
    CODEDESCRIPTION la On la.KCODEDESCID = ql.FLOGACTIONCODEID
            And la.KSYSTEMLANGUAGECODEID = 3 Left Join
    SYSTEMUSER On SYSTEMUSER.KUSERCODE = ql.FAUDITUSERCODE
Where
    ql.FENTRYLEVELCODEID != 2004726
Order By
    ql.AUDITDATETIME