Select
    tend.ia_tend_auto,
    tend.ia_tend_token,
    tend.ia_user_sysid,
    user.name As officer_name,
    user.username As officer_username,
    user.email As officer_email,
    tend.ia_tend_permission,
    tend.ia_tend_customer,
    tend.ia_tend_status,
    tend.ia_tend_yeari,
    tend.ia_tend_sequence,
    tend.ia_tend_number,
    tend.ia_tend_description,
    tend.ia_tend_alternate,
    tend.ia_tend_droplink,
    tend.ia_tend_division,
    tend.ia_tend_owner_name,
    tend.ia_tend_owner_number,
    tend.ia_tend_owner_mail,
    tend.ia_tend_representative_name,
    tend.ia_tend_representative_number,
    tend.ia_tend_representative_mail,
    tend.ia_tend_auditor_id,
    tend.ia_tend_auditor_name,
    tend.ia_tend_auditor_number,
    tend.ia_tend_auditor_mail,
    tend.ia_tend_datesubmit,
    tend.ia_tend_dateadvert,
    tend.ia_tend_dateclose,
    tend.ia_tend_dateopen,
    tend.ia_tend_dateexpect,
    tend.ia_tend_valueexpect,
    tend.ia_tend_valuelow,
    tend.ia_tend_valuehigh,
    tend.ia_tend_dateaward,
    tend.ia_tend_valueaward,
    tend.ia_tend_advert,
    tend.ia_tend_note,
    tend.ia_tend_formedit,
    tend.ia_tend_createby,
    tend.ia_tend_createdate,
    tend.ia_tend_editby,
    tend.ia_tend_editdate,
    tend.ia_assicate_auto,
    cate.ia_assicate_name,
    tend.ia_assisite_auto,
    site.ia_assisite_name,
    tend.ia_assitype_auto,
    tend.ia_assistat_auto
From
    ia_tender tend Inner Join
    jm4_users user On user.id = tend.ia_user_sysid Inner Join
    ia_assignment_category cate On cate.ia_assicate_auto = tend.ia_assicate_auto Inner Join
    ia_assignment_site site On site.ia_assisite_auto = tend.ia_assisite_auto
Where
    tend.ia_tend_token = '412f50c6873e8b8405b1a02656a51117'