Select
    par.KBUSINESSENTITYID,
    par.PARTYTYPE,
    par.FIRSTNAMES,
    par.NAME,
    par.INITIALS,
    par.SURNAME,
    pex.KEXTERNALREFERENCECODEID As EXREF_CODE,
    exc.CODELONGDESCRIPTION As REFERENCE,
    pex.EXTERNALREFERENCENUMBER As REFERENCE_NUMBER,
    pex.STARTDATE,
    pex.ENDDATE,
    pex.REFERENCECODE,
    pex.OTHERDESCRIPTION
From
    PARTY par Inner Join
    PARTYEXTERNALREFERENCE pex On pex.KBUSINESSENTITYID = par.KBUSINESSENTITYID Left Join
    CODEDESCRIPTION exc On exc.KCODEDESCID = pex.KEXTERNALREFERENCECODEID
            And exc.KSYSTEMLANGUAGECODE = 3