Select
    pas.KBUSINESSENTITYID,
    upper(codptyp.CODELONGDESCRIPTION) As PASSWORD_TYPE,
    pas.PASSWORDVALUE As PASSWORD_VALUE,
    pas.AUDITDATETIME,
    pas.FAUDITSYSTEMFUNCTIONID,
    pas.FAUDITUSERCODE
From
    PARTYPINPASSWORD pas Left Join
    CODEDESCRIPTION codptyp On codptyp.KCODEDESCID = pas.KPASSWORDTYPECODEID
            And codptyp.KSYSTEMLANGUAGECODE = 3