Select
    paal.ABSENCE_ATTENDANCE_ID,
    paal.PERSON_ID,
    paal.ATTRIBUTE5 As APPROVED_BY,
    paal.AUTHORISING_PERSON_ID,
    paal.ABSENCE_ATTENDANCE_TYPE_ID,
    Upper(paat.NAME) As LEAVE_TYPE,
    paal.OCCURRENCE,
    paal.ABS_ATTENDANCE_REASON_ID,
    paar.NAME As LEAVE_REASON,
    Upper(paar.MEANING) As LEAVE_MEANING,
    paal.DATE_NOTIFICATION,
    paal.DATE_PROJECTED_START,
    paal.DATE_PROJECTED_END,
    paal.DATE_START,
    paal.DATE_END,
    paal.ABSENCE_DAYS,
    paal.PROGRAM_APPLICATION_ID,
    paal.ATTRIBUTE1 As REFERENCE,
    paal.ATTRIBUTE2 As DATE_FORM,
    paal.ATTRIBUTE3 As DIY_REFERENCE,
    paal.ATTRIBUTE4 As DIY_COMMENT,
    paal.ATTRIBUTE6 As NEAR_PUBLIC_HOLIDAY,
    paal.ATTRIBUTE7 As NEAR_WEEKEND,
    paal.CREATED_BY,
    paal.CREATION_DATE,
    paal.LAST_UPDATE_DATE,
    paal.LAST_UPDATED_BY,
    paal.LAST_UPDATE_LOGIN,
    paal.REASON_FOR_NOTIFICATION_DELAY,
    paal.ACCEPT_LATE_NOTIFICATION_FLAG,
    paal.OBJECT_VERSION_NUMBER
From
    PER_ABSENCE_ATTENDANCES paal Left Join
    PER_ABSENCE_ATTENDANCE_TYPES paat On paat.ABSENCE_ATTENDANCE_TYPE_ID = paal.ABSENCE_ATTENDANCE_TYPE_ID Left Join
    X101_PER_ABS_ATTENDANCE_REASONS paar On paar.ABS_ATTENDANCE_REASON_ID = paal.ABS_ATTENDANCE_REASON_ID
Order By
    paal.CREATION_DATE