Select
    paal.ABSENCE_ATTENDANCE_ID,
    paal.PERSON_ID,
    paal.DATE_NOTIFICATION,
    paal.DATE_PROJECTED_START,
    paal.DATE_PROJECTED_END,
    paal.DATE_START,
    paal.DATE_END,
    paal.ABSENCE_DAYS,
    paal.ABSENCE_ATTENDANCE_TYPE_ID As LEAVE_TYPE_ID,
    paat.LEAVE_TYPE,
    paat.LEAVE_CATEGORY,
    paat.LEAVE_CATEGORY_DESCRIPTION,
    paal.ABS_ATTENDANCE_REASON_ID As LEAVE_REASON_ID,
    paar.LEAVE_REASON,
    paar.LEAVE_REASON_DESCRIPTION,
    paal.ATTRIBUTE5 As APPROVER_PERSON_ID,
    paal.AUTHORISING_PERSON_ID,
    paal.PROGRAM_APPLICATION_ID,
    paal.ATTRIBUTE1 As REFERENCE,
    paal.ATTRIBUTE2 As DATE_FORM,
    paal.ATTRIBUTE3 As DIY_REFERENCE,
    paal.ATTRIBUTE4 As DIY_COMMENT,
    paal.ATTRIBUTE6 As NEAR_PUBLIC_HOLIDAY,
    paal.ATTRIBUTE7 As NEAR_WEEKEND,
    paal.CREATED_BY,
    paal.CREATION_DATE,
    paal.LAST_UPDATED_BY As UPDATED_BY,
    paal.LAST_UPDATE_DATE As UPDATE_DATE,
    paal.LAST_UPDATE_LOGIN As UPDATE_LOGIN,
    paal.REASON_FOR_NOTIFICATION_DELAY,
    paal.ACCEPT_LATE_NOTIFICATION_FLAG,
    paal.OBJECT_VERSION_NUMBER
From
    PER_ABSENCE_ATTENDANCES paal Left Join
    X000_Leave_types paat On paat.ABSENCE_ATTENDANCE_TYPE_ID = paal.ABSENCE_ATTENDANCE_TYPE_ID Left Join
    X000_Leave_reasons paar On paar.ABS_ATTENDANCE_REASON_ID = paal.ABS_ATTENDANCE_REASON_ID
Order By
    paal.CREATION_DATE