Select
    paat.ABSENCE_ATTENDANCE_TYPE_ID,
    Upper(paat.NAME) As LEAVE_TYPE,
    paat.ABSENCE_CATEGORY As LEAVE_CATEGORY,
    Upper(loot.MEANING) As LEAVE_CATEGORY_DESCRIPTION,
    paat.HOURS_OR_DAYS,
    paat.INCREASING_OR_DECREASING_FLAG,
    paat.INPUT_VALUE_ID,
    paat.DATE_EFFECTIVE,
    paat.CREATED_BY,
    paat.CREATION_DATE,
    paat.LAST_UPDATED_BY,
    paat.LAST_UPDATE_DATE,
    paat.LAST_UPDATE_LOGIN
From
    PER_ABSENCE_ATTENDANCE_TYPES paat Left Join
    HR_LOOKUPS loot On loot.LOOKUP_CODE = paat.ABSENCE_CATEGORY
            And loot.LOOKUP_TYPE = 'ABSENCE_CATEGORY'
Order By
    paat.ABSENCE_ATTENDANCE_TYPE_ID