Select
    paar.ABS_ATTENDANCE_REASON_ID,
    paar.NAME As LEAVE_REASON,
    Upper(loor.MEANING) As LEAVE_REASON_DESCRIPTION,
    paar.ABSENCE_ATTENDANCE_TYPE_ID,
    Upper(paat.NAME) As LEAVE_TYPE,
    paat.ABSENCE_CATEGORY As LEAVE_CATEGORY,
    Upper(loot.MEANING) As LEAVE_CATEGORY_DESCRIPTION,
    paat.HOURS_OR_DAYS,
    paat.INCREASING_OR_DECREASING_FLAG,
    paat.INPUT_VALUE_ID,
    paar.CREATED_BY,
    paar.CREATION_DATE,
    paar.LAST_UPDATED_BY,
    paar.LAST_UPDATE_DATE,
    paar.LAST_UPDATE_LOGIN
From
    PER_ABS_ATTENDANCE_REASONS paar Left Join
    PER_ABSENCE_ATTENDANCE_TYPES paat On paat.ABSENCE_ATTENDANCE_TYPE_ID = paar.ABSENCE_ATTENDANCE_TYPE_ID Left Join
    HR_LOOKUPS loor On loor.LOOKUP_CODE = paar.NAME
            And loor.LOOKUP_TYPE = 'ABSENCE_REASON' Left Join
    HR_LOOKUPS loot On loot.LOOKUP_CODE = paat.ABSENCE_CATEGORY
            And loot.LOOKUP_TYPE = 'ABSENCE_CATEGORY'
Order By
    paar.ABS_ATTENDANCE_REASON_ID