Select
    BUSINESSENTITYTELEPHONE.KBUSINESSENTITYID,
    BUSINESSENTITYTELEPHONE.INTERNATIONALDIALCODE,
    BUSINESSENTITYTELEPHONE.AREADIALCODE,
    BUSINESSENTITYTELEPHONE.TELEPHONENUMBER,
    BUSINESSENTITYTELEPHONE.EXTENSION,
    CODEDESCRIPTION.CODELONGDESCRIPTION,
    CODEDESCRIPTION.CODESHORTDESCRIPTION
From
    BUSINESSENTITYTELEPHONE Left Join
    CODEDESCRIPTION On CODEDESCRIPTION.KCODEDESCID = BUSINESSENTITYTELEPHONE.KTELEPHONEPURPOSECODEID